In [1]:
import numpy as np

In [2]:
nums = [1,2,3]

In [3]:
print map(lambda x: x*x, nums)

[1, 4, 9]


In [4]:
a=[[1, 2, 3],[4, 5, 6]]

In [5]:
a

[[1, 2, 3], [4, 5, 6]]

In [6]:
a = np.array(a)

In [7]:
a[0][:]

array([1, 2, 3])

In [8]:
a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a[:,0]

array([1, 4])

In [10]:
b=[[1, 2, 3],[4, 5, 6]]

In [11]:
b[:,0]

TypeError: list indices must be integers, not tuple

In [12]:
a[:3,1]

array([2, 5])

In [13]:
a[:,0]

array([1, 4])

In [14]:
np.__version__

'1.11.3'

In [16]:
b[-1:]

[[4, 5, 6]]

In [17]:
print b

[[1, 2, 3], [4, 5, 6]]


In [22]:
print 'список: {}\n'.format(b),'список: {}'.format(a)

список: [[1, 2, 3], [4, 5, 6]]
список: [[1 2 3]
 [4 5 6]]


In [23]:
print 'список: {}'.format(b),'список: {}'.format(a)

список: [[1, 2, 3], [4, 5, 6]] список: [[1 2 3]
 [4 5 6]]


In [25]:
print 'список: {}'.format(b),'список: {}'.format(a)

список: [[1, 2, 3], [4, 5, 6]] список: [[1 2 3]
 [4 5 6]]


In [30]:
print 'список:\n', b,'\n','список:\n', a

список:
[[1, 2, 3], [4, 5, 6]] 
список:
[[1 2 3]
 [4 5 6]]
